/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.teamsight.touchvision.sistelnetworks.vwandtestingtool;

public final class R {
    public static final class array {
        public static final int URI_Identifier_Code=0x7f070000;
    }
    public static final class attr {
    }
    public static final class color {
        /**  Background 
         */
        public static final int background_color=0x7f040004;
        public static final int background_gradient_end=0x7f040006;
        public static final int background_gradient_end2=0x7f040009;
        public static final int background_gradient_start=0x7f040005;
        public static final int background_gradient_start2=0x7f040008;
        public static final int background_gradient_stroke=0x7f040007;
        public static final int background_panel=0x7f04000a;
        /**  Buttons 
         */
        public static final int button_solid=0x7f04000c;
        public static final int dark_green_text_color=0x7f040002;
        public static final int default_text_color=0x7f040000;
        public static final int disabled_border=0x7f04001a;
        public static final int disabled_center=0x7f040018;
        public static final int disabled_end=0x7f040019;
        public static final int disabled_start=0x7f040017;
        public static final int disabled_text=0x7f04001b;
        public static final int green_text_color=0x7f040001;
        public static final int normal_border=0x7f040010;
        public static final int normal_center=0x7f04000e;
        public static final int normal_end=0x7f04000f;
        public static final int normal_start=0x7f04000d;
        public static final int normal_text=0x7f040011;
        public static final int panel_border=0x7f04000b;
        public static final int pressed_border=0x7f040015;
        public static final int pressed_center=0x7f040013;
        public static final int pressed_end=0x7f040014;
        public static final int pressed_start=0x7f040012;
        public static final int pressed_text=0x7f040016;
        public static final int transparent_white=0x7f040003;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f050007;
        public static final int activity_vertical_margin=0x7f050008;
        public static final int button_corner=0x7f050001;
        public static final int button_height=0x7f050005;
        public static final int button_padding=0x7f050000;
        public static final int corner_radius=0x7f050002;
        public static final int half_button_height=0x7f050006;
        public static final int layer_padding=0x7f050004;
        public static final int stroke_width=0x7f050003;
    }
    public static final class drawable {
        public static final int background_app=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int icon_vwand_app_600dpi_tectiles=0x7f020002;
        public static final int sistelnetworks=0x7f020003;
        public static final int vwand13=0x7f020004;
        public static final int vwand_big=0x7f020005;
    }
    public static final class id {
        public static final int FrameLayout1=0x7f0a0005;
        public static final int RelativeLayout1=0x7f0a0000;
        public static final int btnConnect=0x7f0a0001;
        public static final int btnRead=0x7f0a0002;
        public static final int btnWrite=0x7f0a0003;
        public static final int ctrlActivityIndicator=0x7f0a0004;
        public static final int etContentWrite=0x7f0a000f;
        public static final int imageView1=0x7f0a0007;
        public static final int linearLayout1=0x7f0a0006;
        public static final int spiWrite=0x7f0a000e;
        public static final int textView1=0x7f0a0008;
        public static final int textView2=0x7f0a000a;
        public static final int textView3=0x7f0a000c;
        public static final int tvContent=0x7f0a000d;
        public static final int tvType=0x7f0a000b;
        public static final int txUID=0x7f0a0009;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int bdevices=0x7f030001;
        public static final int progressconnecting=0x7f030002;
        public static final int read=0x7f030003;
        public static final int write=0x7f030004;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class string {
        public static final int action_settings=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int hello_world=0x7f060002;
        public static final int loading=0x7f060003;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
    }
}
